packages:
  - backend
  - frontend
  - worker
  - packages/*

onlyBuiltDependencies:
  - prisma
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - workerd
  - '@tailwindcss/oxide'
  - '@nestjs/core'
