import {
  Inject,
  Injectable,
  Logger,
  ServiceUnavailableException,
  UnauthorizedException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  AuditAction,
  ConnectionProvider,
  ConnectionStatus,
  Prisma,
} from '@prisma/client';
import { timingSafeEqual } from 'crypto';
import Redis from 'ioredis';
import { TokenCipher } from '../../common/crypto/token-cipher';
import { PrismaService } from '../../prisma/prisma.service';
import { REDIS_CLIENT } from '../../redis/redis.module';
import { AuditLogService } from '../../shared/audit-log.service';
import { AuthService } from '../auth.service';
import {
  GOOGLE_AUTHORIZE_URL,
  GOOGLE_TOKEN_URL,
  GoogleIdentity,
  GoogleTokenResponse,
  SIGN_IN_SCOPES,
  isGoogleTokenResponse,
  pkceChallenge,
  randomToken,
  readIdTokenFromTokenEndpoint,
  sanitizeReturnTo,
} from './google-oauth';

const STATE_TTL_SECONDS = 10 * 60;
// Just long enough for the dashboard's callback page to load and exchange it.
const HANDOFF_TTL_SECONDS = 60;
const TOKEN_EXCHANGE_TIMEOUT_MS = 10_000;
const MIN_NONCE_LENGTH = 16;
const STATE_KEY_PREFIX = 'oauth:google:state:';
const HANDOFF_KEY_PREFIX = 'oauth:google:handoff:';

/**
 * Error codes surfaced to the dashboard as /login?error=<code>. Mirrored by
 * `GoogleSignInError` in packages/api-types — change both together.
 */
export type GoogleSignInError =
  | 'access_denied'
  | 'state_expired'
  | 'email_unverified'
  | 'account_conflict'
  | 'google_failed';

interface PendingSignIn {
  codeVerifier: string;
  returnTo: string;
  nonce: string;
}

interface UpsertOutcome {
  userId: string;
  event?: { action: AuditAction; name: string };
}

interface Handoff {
  userId: string;
  nonce: string;
}

export class GoogleSignInFailure extends Error {
  constructor(readonly code: GoogleSignInError) {
    super(code);
  }
}

/**
 * Google is the only way to sign in. The flow is authorization code + PKCE,
 * run server-side so the client secret and Google's tokens never reach the
 * browser:
 *
 *   dashboard → GET /auth/google/start ─302→ Google ─302→ GET /auth/google/callback
 *     → upsert user + Connection → 302 dashboard /auth/callback?code=<handoff>
 *     → POST /auth/google/exchange { code, nonce } → FlowState token pair
 *
 * The handoff code exists because the API and dashboard are on different
 * origins: putting the session tokens themselves in a redirect URL would
 * leak them into history and logs. The nonce is generated by the dashboard,
 * kept in sessionStorage, and must match at exchange time — that binds the
 * whole flow to the tab that started it, which is what stops login CSRF
 * (someone sending you a link that signs you into *their* account).
 */
@Injectable()
export class GoogleAuthService {
  private readonly logger = new Logger(GoogleAuthService.name);

  constructor(
    private readonly config: ConfigService,
    private readonly prisma: PrismaService,
    private readonly authService: AuthService,
    private readonly auditLog: AuditLogService,
    @Inject(REDIS_CLIENT) private readonly redis: Redis,
  ) {}

  async buildAuthorizationUrl(
    returnTo: unknown,
    nonce: unknown,
  ): Promise<string> {
    const { clientId } = this.requireConfig();
    if (typeof nonce !== 'string' || nonce.length < MIN_NONCE_LENGTH) {
      throw new UnauthorizedException('A sign-in nonce is required');
    }

    const state = randomToken();
    const codeVerifier = randomToken();
    const pending: PendingSignIn = {
      codeVerifier,
      returnTo: sanitizeReturnTo(returnTo),
      nonce,
    };
    await this.redis.set(
      STATE_KEY_PREFIX + state,
      JSON.stringify(pending),
      'EX',
      STATE_TTL_SECONDS,
    );

    const url = new URL(GOOGLE_AUTHORIZE_URL);
    url.search = new URLSearchParams({
      client_id: clientId,
      redirect_uri: this.redirectUri(),
      response_type: 'code',
      scope: SIGN_IN_SCOPES.join(' '),
      state,
      code_challenge: pkceChallenge(codeVerifier),
      code_challenge_method: 'S256',
      // Offline + granted-scope merging so the refresh token stored at
      // sign-in keeps working once app scopes are added later.
      access_type: 'offline',
      include_granted_scopes: 'true',
      prompt: 'select_account',
    }).toString();
    return url.toString();
  }

  /**
   * Handles Google's redirect back. Always resolves to a dashboard URL —
   * this is a browser navigation, so failures become /login?error=<code>
   * rather than a JSON error page the user can't act on.
   */
  async handleCallback(query: Record<string, unknown>): Promise<string> {
    try {
      if (typeof query.error === 'string') {
        throw new GoogleSignInFailure('access_denied');
      }
      if (typeof query.state !== 'string' || typeof query.code !== 'string') {
        throw new GoogleSignInFailure('state_expired');
      }

      const pending = await this.takePending(query.state);
      const tokens = await this.exchangeCode(query.code, pending.codeVerifier);
      const identity = readIdTokenFromTokenEndpoint(
        tokens.id_token,
        this.requireConfig().clientId,
      );
      if (!identity.emailVerified) {
        throw new GoogleSignInFailure('email_unverified');
      }

      const { userId, event } = await this.upsertUser(identity, tokens);
      if (event) {
        // Logged after the transaction commits — the audit row references
        // a user that doesn't exist until then.
        this.auditLog.log(userId, event.action, {
          entityType: 'users',
          entityId: userId,
          event: event.name,
        });
      }
      const handoff = randomToken();
      const value: Handoff = { userId, nonce: pending.nonce };
      await this.redis.set(
        HANDOFF_KEY_PREFIX + handoff,
        JSON.stringify(value),
        'EX',
        HANDOFF_TTL_SECONDS,
      );

      const url = new URL('/auth/callback', this.frontendUrl());
      url.searchParams.set('code', handoff);
      url.searchParams.set('returnTo', pending.returnTo);
      return url.toString();
    } catch (error) {
      const code =
        error instanceof GoogleSignInFailure ? error.code : 'google_failed';
      if (code === 'google_failed') {
        this.logger.error(
          `Google sign-in failed: ${error instanceof Error ? error.message : String(error)}`,
        );
      }
      const url = new URL('/login', this.frontendUrl());
      url.searchParams.set('error', code);
      return url.toString();
    }
  }

  async exchangeHandoff(code: string, nonce: string) {
    const raw = await this.redis.getdel(HANDOFF_KEY_PREFIX + code);
    const handoff = raw ? (JSON.parse(raw) as Handoff) : null;
    if (!handoff || !safeEqual(handoff.nonce, nonce)) {
      throw new UnauthorizedException('Sign-in link is invalid or expired');
    }
    return this.authService.startSession(handoff.userId);
  }

  private async takePending(state: string): Promise<PendingSignIn> {
    // GETDEL makes the state single-use: a replayed callback finds nothing.
    const raw = await this.redis.getdel(STATE_KEY_PREFIX + state);
    if (!raw) throw new GoogleSignInFailure('state_expired');
    return JSON.parse(raw) as PendingSignIn;
  }

  private async exchangeCode(
    code: string,
    codeVerifier: string,
  ): Promise<GoogleTokenResponse> {
    const { clientId, clientSecret } = this.requireConfig();
    const controller = new AbortController();
    const timeout = setTimeout(
      () => controller.abort(),
      TOKEN_EXCHANGE_TIMEOUT_MS,
    );

    try {
      const response = await fetch(GOOGLE_TOKEN_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          code,
          client_id: clientId,
          client_secret: clientSecret,
          redirect_uri: this.redirectUri(),
          grant_type: 'authorization_code',
          code_verifier: codeVerifier,
        }),
        signal: controller.signal,
      });
      const body: unknown = await response.json();
      if (!response.ok || !isGoogleTokenResponse(body)) {
        throw new Error(`Token exchange failed with HTTP ${response.status}`);
      }
      return body;
    } finally {
      clearTimeout(timeout);
    }
  }

  /**
   * Returning Google account → its user. Otherwise an existing user with
   * the same (Google-verified) email is linked — that's how accounts from
   * the email+password era carry over. Otherwise a new user is created.
   * Concurrent first sign-ins race on the Connection unique constraints;
   * the loser retries once and takes the "returning" path.
   */
  private async upsertUser(
    identity: GoogleIdentity,
    tokens: GoogleTokenResponse,
  ): Promise<UpsertOutcome> {
    const cipher = this.cipher();
    const credentials = {
      email: identity.email,
      scopes: tokens.scope.split(' ').filter(Boolean),
      accessTokenEnc: cipher.encrypt(tokens.access_token),
      accessTokenExpiresAt: new Date(Date.now() + tokens.expires_in * 1000),
      status: ConnectionStatus.ACTIVE,
      // Google only returns a refresh token on first consent — keep the
      // stored one rather than overwriting it with nothing.
      ...(tokens.refresh_token
        ? { refreshTokenEnc: cipher.encrypt(tokens.refresh_token) }
        : {}),
    };

    for (let attempt = 0; ; attempt++) {
      try {
        return await this.prisma.$transaction(async (tx) => {
          const existing = await tx.connection.findUnique({
            where: {
              provider_providerAccountId: {
                provider: ConnectionProvider.GOOGLE,
                providerAccountId: identity.sub,
              },
            },
          });
          if (existing) {
            await tx.connection.update({
              where: { id: existing.id },
              data: credentials,
            });
            return { userId: existing.userId };
          }

          const connection = {
            provider: ConnectionProvider.GOOGLE,
            providerAccountId: identity.sub,
            ...credentials,
          };

          const byEmail = await tx.user.findUnique({
            where: { email: identity.email },
            include: {
              connections: { where: { provider: ConnectionProvider.GOOGLE } },
            },
          });
          if (byEmail) {
            if (byEmail.connections.length > 0) {
              // This email belongs to a user already tied to a *different*
              // Google account. Never silently re-point it.
              throw new GoogleSignInFailure('account_conflict');
            }
            await tx.connection.create({
              data: { ...connection, userId: byEmail.id },
            });
            return {
              userId: byEmail.id,
              event: { action: AuditAction.UPDATE, name: 'auth.google.linked' },
            };
          }

          const user = await tx.user.create({
            data: {
              email: identity.email,
              name: identity.name,
              connections: { create: connection },
            },
          });
          return {
            userId: user.id,
            event: {
              action: AuditAction.CREATE,
              name: 'auth.google.registered',
            },
          };
        });
      } catch (error) {
        const isUniqueRace =
          error instanceof Prisma.PrismaClientKnownRequestError &&
          error.code === 'P2002';
        if (!isUniqueRace || attempt > 0) throw error;
      }
    }
  }

  private requireConfig() {
    const clientId = this.config.get<string>('GOOGLE_CLIENT_ID');
    const clientSecret = this.config.get<string>('GOOGLE_CLIENT_SECRET');
    const encryptionKey = this.config.get<string>('CREDENTIALS_ENCRYPTION_KEY');
    // Checked per request rather than at boot so a missing Google setup
    // disables sign-in with a clear message instead of stopping the API.
    if (!clientId || !clientSecret || !encryptionKey) {
      throw new ServiceUnavailableException(
        'Google sign-in is not configured: set GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET and CREDENTIALS_ENCRYPTION_KEY',
      );
    }
    let cipher: TokenCipher;
    try {
      cipher = new TokenCipher(encryptionKey);
    } catch (error) {
      throw new ServiceUnavailableException(
        error instanceof Error ? error.message : 'Invalid encryption key',
      );
    }
    return { clientId, clientSecret, cipher };
  }

  private cipher() {
    return this.requireConfig().cipher;
  }

  private redirectUri() {
    return this.config.get<string>(
      'GOOGLE_REDIRECT_URI',
      `http://localhost:${this.config.get<string>('PORT', '3000')}/auth/google/callback`,
    );
  }

  private frontendUrl() {
    return this.config.get<string>('FRONTEND_URL', 'http://localhost:5173');
  }
}

function safeEqual(a: string, b: string): boolean {
  const left = Buffer.from(a);
  const right = Buffer.from(b);
  return left.length === right.length && timingSafeEqual(left, right);
}
