-- FlowState schema for Cloudflare D1 (SQLite).
--
-- Mirrors backend/prisma/schema.prisma (the NestJS backend's Postgres schema)
-- table for table and column for column, so data moves across unchanged
-- (scripts/postgres-to-d1.mjs). Type mapping:
--   uuid            → TEXT (generated by the Worker, never the database)
--   enum            → TEXT + CHECK
--   jsonb, text[]   → TEXT holding JSON
--   timestamp       → TEXT, ISO-8601 UTC ("2026-09-27T10:15:00.000Z") — sorts
--                     and compares correctly as text, and has no time zone
--                     for a session to misread
--   boolean         → INTEGER 0/1
--   bigint          → INTEGER (SQLite integers are 64-bit)
-- D1 enforces foreign keys, so ON DELETE behaviour matches Postgres.

CREATE TABLE users (
  id         TEXT PRIMARY KEY,
  email      TEXT NOT NULL UNIQUE,
  name       TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE connections (
  id                      TEXT PRIMARY KEY,
  user_id                 TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider                TEXT NOT NULL CHECK (provider IN ('GOOGLE')),
  provider_account_id     TEXT NOT NULL,
  email                   TEXT NOT NULL,
  scopes                  TEXT NOT NULL DEFAULT '[]',
  access_token_enc        TEXT,
  refresh_token_enc       TEXT,
  access_token_expires_at TEXT,
  status                  TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'NEEDS_REAUTH')),
  created_at              TEXT NOT NULL,
  updated_at              TEXT NOT NULL,
  UNIQUE (provider, provider_account_id),
  UNIQUE (user_id, provider)
);

CREATE TABLE refresh_tokens (
  id                   TEXT PRIMARY KEY,
  token_hash           TEXT NOT NULL,
  user_id              TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at           TEXT NOT NULL,
  revoked_at           TEXT,
  replaced_by_token_id TEXT REFERENCES refresh_tokens(id) ON DELETE SET NULL,
  created_at           TEXT NOT NULL
);
CREATE INDEX refresh_tokens_user_id_idx ON refresh_tokens(user_id);

CREATE TABLE workflows (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  description TEXT,
  status      TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED')),
  version     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX workflows_user_id_idx ON workflows(user_id);

-- workflow_id UNIQUE = exactly one trigger per workflow.
CREATE TABLE triggers (
  id          TEXT PRIMARY KEY,
  workflow_id TEXT NOT NULL UNIQUE REFERENCES workflows(id) ON DELETE CASCADE,
  type        TEXT NOT NULL CHECK (type IN ('WEBHOOK', 'MANUAL', 'SCHEDULED')),
  config      TEXT NOT NULL DEFAULT '{}',
  secret      TEXT,
  enabled     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

CREATE TABLE polling_events (
  id                TEXT PRIMARY KEY,
  trigger_id        TEXT NOT NULL REFERENCES triggers(id) ON DELETE CASCADE,
  polled_at         TEXT NOT NULL,
  changed           INTEGER NOT NULL,
  response_snapshot TEXT,
  error             TEXT
);
CREATE INDEX polling_events_trigger_id_idx ON polling_events(trigger_id);
CREATE INDEX polling_events_polled_at_idx ON polling_events(polled_at);

-- (workflow_id, idempotency_key) UNIQUE is the whole webhook dedup guarantee.
CREATE TABLE webhook_events (
  id              TEXT PRIMARY KEY,
  workflow_id     TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  payload         TEXT NOT NULL,
  received_at     TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'RECEIVED',
  idempotency_key TEXT,
  created_at      TEXT NOT NULL,
  UNIQUE (workflow_id, idempotency_key)
);
CREATE INDEX webhook_events_workflow_id_idx ON webhook_events(workflow_id);
CREATE INDEX webhook_events_status_idx ON webhook_events(status);

CREATE TABLE conditions (
  id          TEXT PRIMARY KEY,
  workflow_id TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,
  expression  TEXT NOT NULL,
  position    INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX conditions_workflow_id_idx ON conditions(workflow_id);

CREATE TABLE actions (
  id          TEXT PRIMARY KEY,
  workflow_id TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,
  config      TEXT NOT NULL,
  position    INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX actions_workflow_id_idx ON actions(workflow_id);

CREATE TABLE workflow_executions (
  id          TEXT PRIMARY KEY,
  workflow_id TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  trigger_id  TEXT REFERENCES triggers(id) ON DELETE SET NULL,
  status      TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
  input       TEXT,
  output      TEXT,
  error       TEXT,
  started_at  TEXT,
  finished_at TEXT,
  created_at  TEXT NOT NULL
);
CREATE INDEX workflow_executions_workflow_id_idx ON workflow_executions(workflow_id);
CREATE INDEX workflow_executions_trigger_id_idx ON workflow_executions(trigger_id);
-- The runs list filters by status and sorts newest first.
CREATE INDEX workflow_executions_status_idx ON workflow_executions(status);
CREATE INDEX workflow_executions_created_at_idx ON workflow_executions(created_at);

CREATE TABLE action_executions (
  id                    TEXT PRIMARY KEY,
  workflow_execution_id TEXT NOT NULL REFERENCES workflow_executions(id) ON DELETE CASCADE,
  action_id             TEXT NOT NULL REFERENCES actions(id) ON DELETE CASCADE,
  status                TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
  input                 TEXT,
  output                TEXT,
  error                 TEXT,
  started_at            TEXT,
  finished_at           TEXT,
  created_at            TEXT NOT NULL
);
CREATE INDEX action_executions_workflow_execution_id_idx ON action_executions(workflow_execution_id);
CREATE INDEX action_executions_action_id_idx ON action_executions(action_id);

CREATE TABLE audit_logs (
  id          TEXT PRIMARY KEY,
  user_id     TEXT REFERENCES users(id) ON DELETE SET NULL,
  action      TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id   TEXT,
  metadata    TEXT,
  ip_address  TEXT,
  user_agent  TEXT,
  created_at  TEXT NOT NULL
);
CREATE INDEX audit_logs_user_id_idx ON audit_logs(user_id);
CREATE INDEX audit_logs_entity_type_entity_id_idx ON audit_logs(entity_type, entity_id);

CREATE TABLE telegram_users (
  id            TEXT PRIMARY KEY,
  telegram_id   INTEGER NOT NULL UNIQUE,
  chat_id       INTEGER NOT NULL UNIQUE,
  username      TEXT,
  first_name    TEXT,
  last_name     TEXT,
  language_code TEXT,
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
